"""Change telegram_id to BigInteger

Revision ID: 2bf3ee2d5bc5
Revises: 91334872ad25
Create Date: 2024-09-30 19:24:12.534153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf3ee2d5bc5'
down_revision: Union[str, None] = '91334872ad25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='telegram_id::bigint')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
