"""empty message

Revision ID: 6b905a26cf18
Revises: 517a06bd6efd
Create Date: 2024-09-27 16:52:03.783106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b905a26cf18'
down_revision: Union[str, None] = '517a06bd6efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
