"""Initial migration

Revision ID: 8137f25a12ce
Revises: a4cb4f59cc9d
Create Date: 2024-09-30 18:56:38.510776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8137f25a12ce'
down_revision: Union[str, None] = 'a4cb4f59cc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
