"""Add telegram_id to User model

Revision ID: aeb61e290229
Revises: ec054c5002d7
Create Date: 2024-09-29 19:36:59.804835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb61e290229'
down_revision: Union[str, None] = 'ec054c5002d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем колонку telegram_id с временным nullable=True
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))

    # Обновляем существующие записи, чтобы в колонке telegram_id не было NULL
    op.execute('UPDATE users SET telegram_id = 0 WHERE telegram_id IS NULL')

    # Изменяем колонку telegram_id, делаем ее обязательной (nullable=False)
    op.alter_column('users', 'telegram_id', nullable=False)

    # Создаем уникальное ограничение на колонку telegram_id
    op.create_unique_constraint(None, 'users', ['telegram_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###